### ISSUE TITLE
Tableau Service Management vs Tableau Server

### ISSUE THREAD

**Issue by ghost-code-ninja** [desperado0105/tableau_trusted_authentication_api#1]
I am a beginner of Tableau.
I have gone through the Trusted Authentication on Tableau online help.

But I found that to add the web server IP address to https://tsm-computer-name:8850.
And I found that Tableau Server domain and Ip address are also required.

So I just want to know the following questions.

Are Tableau Server and Tableau Service Management on different computers?
If so, where should TSM be installed?
How do I create a TSM credential (admin)?

**Comment by desperado0105** [comment]
TSM will be pre-installed with Tableau Server on the same machine while you are running the installation process, u don't need to install it separately. And to visit TSM web UI you can just change the port number to 8850.

> How do I create a TSM credential (admin)?

u need to add whatever OS user into user group 'tsmadmin'.
[https://onlinehelp.tableau.com/current/server-linux/en-us/tsm_overview.htm#authentication](https://onlinehelp.tableau.com/current/server-linux/en-us/tsm_overview.htm#authentication)

**Comment by desperado0105** [comment]
> TSM will be pre-installed with Tableau Server on the same machine while you are running the installation process, u don't need to install it separately. And to visit TSM web UI you can just change the port number to 8850.
> 
> > How do I create a TSM credential (admin)?
> 
> u need to add whatever OS user into user group 'tsmadmin'.
> https://onlinehelp.tableau.com/current/server-linux/en-us/tsm_overview.htm#authentication

**Comment by rjhong** [comment]
> I am a beginner of Tableau.
> I have gone through the Trusted Authentication on Tableau online help.
> 
> But I found that to add the web server IP address to https://tsm-computer-name:8850.
> And I found that Tableau Server domain and Ip address are also required.
> 
> So I just want to know the following questions.
> 
> Are Tableau Server and Tableau Service Management on different computers?
> If so, where should TSM be installed?
> How do I create a TSM credential (admin)?

TSM will be pre-installed with Tableau Server on the same machine while you are running the installation process, u don't need to install it separately. And to visit TSM web UI you can just change the port number to 8850.

> How do I create a TSM credential (admin)?

u need to add whatever OS user into user group 'tsmadmin'. There should be a default one, u can check who exists in 'tsmadmin', use that, better than adding new users into the group.
[https://onlinehelp.tableau.com/current/server-linux/en-us/tsm_overview.htm#authentication](https://onlinehelp.tableau.com/current/server-linux/en-us/tsm_overview.htm#authentication)
